version: "3.6"
services:
  ptransp:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: ptransp
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - /var/www/node_modules
      - ./vendor:/var/www/vendor
  ntransp:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile.dev
    container_name: ntransp
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: nginx
      SERVICE_TAGS: dev
    ports:
      - ${WEBSERVER_PORT}:80
      - 443:443
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ptransp
networks: 
  default: 
    external: true
    name: one80-network 
